spring:
  debug: true
  output:
    ansi:
      enabled=ALWAYS:

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    initialization-mode: always
    hikari:
      connectionTimeout: 45000

  jpa:
    #show-sql: true
    #generate-ddl : true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    properties:
      hibernate:
        format_sql: true
        dialect:       "org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect"
    database-platform: "org.hibernate.spatial.dialect.mysql.MySQLSpatial56Dialect"

  application:
    name: "web"

logging:
  level:
    org:
      springframework:
        web: "DEBUG"
      #hibernate:
      #  SQL: "DEBUG"
      #  type: "TRACE"


